import { 
    Briefcase, Heart, Dumbbell, Wallet, BookOpen, Lightbulb, BrainCircuit, 
    Target, PencilRuler, LineChart, Code, Palette, Music, Clapperboard, 
    Gamepad2, Plane, Utensils, MessageCircle, Users, GitBranch, Archive, 
  Map, GraduationCap, Home, Hammer, Sprout, Star, Award, Flag,
    Component, ClipboardList, Settings, Shield, Trophy, Bike, Car, FileText,
    Camera, type LucideIcon 
} from 'lucide-react';

export const iconMap: { [key: string]: LucideIcon } = {
  Briefcase,
  Heart,
  Dumbbell,
  Wallet,
  BookOpen,
  Lightbulb,
  BrainCircuit,
  Target,
  PencilRuler,
  LineChart,
  Code,
  Palette,
  Music,
  Clapperboard,
  Gamepad2,
  Plane,
  Utensils,
  MessageCircle,
  Users,
  GitBranch,
  Archive,
  Map,
  GraduationCap,
  Home,
  Hammer,
  Sprout,
  Star,
  Award,
  Flag,
  Component,
  ClipboardList,
  Settings,
  Shield,
  Trophy,
  Bike,
  Car,
  FileText,
  Camera,
};
