import { Briefcase, Heart, Dumbbell, Wallet, BookOpen, Lightbulb, type LucideIcon, BrainCircuit, Target, PencilRuler, LineChart, Code, Palette, Music, Clapperboard, Gamepad2, Plane, Utensils, MessageCircle, Users, GitBranch, Archive } from 'lucide-react';

export const iconMap: { [key: string]: LucideIcon } = {
  Briefcase,
  Heart,
  Dumbbell,
  Wallet,
  BookOpen,
  Lightbulb,
  BrainCircuit,
  Target,
  PencilRuler,
  LineChart,
  Code,
  Palette,
  Music,
  Clapperboard,
  Gamepad2,
  Plane,
  Utensils,
  MessageCircle,
  Users,
  GitBranch,
  Archive,
};
